# \u9879\u76EE\u8BBF\u95EE\u8DEF\u5F84
spring:
  datasource:
    url: jdbc:mysql://192.168.232.1:3306/department
    username: root
    password: 970420
    driver-class-name: com.mysql.jdbc.Driver
  # \u56FD\u9645\u5316\u914D\u7F6E\u6587\u4EF6\uFF08\u5305\u540D.\u57FA\u7840\u540D\uFF09
  messages:
    basename: i18n.login
  # \u7981\u7528\u7F13\u5B58
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
server:
  context-path: /crud
  port: 8081
  tomcat:
    uri-encoding: utf-8